import type { Config } from 'tailwindcss';

export default {
  darkMode: ['class'],
  content: ['./pages/**/*.{ts,tsx}', './components/**/*.{ts,tsx}', './app/**/*.{ts,tsx}', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      colors: {
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        chart: {
          '1': 'hsl(var(--chart-1))',
          '2': 'hsl(var(--chart-2))',
          '3': 'hsl(var(--chart-3))',
          '4': 'hsl(var(--chart-4))',
          '5': 'hsl(var(--chart-5))',
        },
        sidebar: {
          DEFAULT: 'hsl(var(--sidebar-background))',
          foreground: 'hsl(var(--sidebar-foreground))',
          primary: 'hsl(var(--sidebar-primary))',
          'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
          accent: 'hsl(var(--sidebar-accent))',
          'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
          border: 'hsl(var(--sidebar-border))',
          ring: 'hsl(var(--sidebar-ring))',
        },
        black: 'var(--black)',
        grey: {
          10: 'var(--grey10)',
          50: 'var(--grey50)',
          100: 'var(--grey100)',
          200: 'var(--grey200)',
          300: 'var(--grey300)',
          400: 'var(--grey400)',
          500: 'var(--grey500)',
          600: 'var(--grey600)',
          700: 'var(--grey700)',
          800: 'var(--grey800)',
          900: 'var(--grey900)',
        },
        white: 'var(--white)',
        orange: {
          50: 'var(--orange50)',
          100: 'var(--orange100)',
          150: 'var(--orange150)',
          200: 'var(--orange200)',
          250: 'var(--orange250)',
          300: 'var(--orange300)',
          350: 'var(--orange350)',
          400: 'var(--orange400)',
          450: 'var(--orange450)',
          500: 'var(--orange500)',
          550: 'var(--orange550)',
          600: 'var(--orange600)',
          650: 'var(--orange650)',
          700: 'var(--orange700)',
          750: 'var(--orange750)',
          800: 'var(--orange800)',
          850: 'var(--orange850)',
          900: 'var(--orange900)',
          950: 'var(--orange950)',
        },
        red: {
          50: 'var(--red50)',
          100: 'var(--red100)',
          150: 'var(--red150)',
          200: 'var(--red200)',
          250: 'var(--red250)',
          300: 'var(--red300)',
          350: 'var(--red350)',
          400: 'var(--red400)',
          450: 'var(--red450)',
          500: 'var(--red500)',
          550: 'var(--red550)',
          600: 'var(--red600)',
          650: 'var(--red650)',
          700: 'var(--red700)',
          750: 'var(--red750)',
          800: 'var(--red800)',
          850: 'var(--red850)',
          900: 'var(--red900)',
          950: 'var(--red950)',
        },
        blue: {
          50: 'var(--blue50)',
          100: 'var(--blue100)',
          150: 'var(--blue150)',
          200: 'var(--blue200)',
          250: 'var(--blue250)',
          300: 'var(--blue300)',
          350: 'var(--blue350)',
          400: 'var(--blue400)',
          450: 'var(--blue450)',
          500: 'var(--blue500)',
          550: 'var(--blue550)',
          600: 'var(--blue600)',
          650: 'var(--blue650)',
          700: 'var(--blue700)',
          750: 'var(--blue750)',
          800: 'var(--blue800)',
          850: 'var(--blue850)',
          900: 'var(--blue900)',
          950: 'var(--blue950)',
        },
        teal: {
          50: 'var(--teal50)',
          100: 'var(--teal100)',
          150: 'var(--teal150)',
          200: 'var(--teal200)',
          250: 'var(--teal250)',
          300: 'var(--teal300)',
          350: 'var(--teal350)',
          400: 'var(--teal400)',
          450: 'var(--teal450)',
          500: 'var(--teal500)',
          550: 'var(--teal550)',
          600: 'var(--teal600)',
          650: 'var(--teal650)',
          700: 'var(--teal700)',
          750: 'var(--teal750)',
          800: 'var(--teal800)',
          850: 'var(--teal850)',
          900: 'var(--teal900)',
          950: 'var(--teal950)',
        },
        purple: {
          50: 'var(--purple50)',
          100: 'var(--purple100)',
          150: 'var(--purple150)',
          200: 'var(--purple200)',
          250: 'var(--purple250)',
          300: 'var(--purple300)',
          350: 'var(--purple350)',
          400: 'var(--purple400)',
          450: 'var(--purple450)',
          500: 'var(--purple500)',
          550: 'var(--purple550)',
          600: 'var(--purple600)',
          650: 'var(--purple650)',
          700: 'var(--purple700)',
          750: 'var(--purple750)',
          800: 'var(--purple800)',
          850: 'var(--purple850)',
          900: 'var(--purple900)',
          950: 'var(--purple950)',
        },
        'ui-red': {
          50: 'var(--ui-red50)',
          100: 'var(--ui-red100)',
          200: 'var(--ui-red200)',
          300: 'var(--ui-red300)',
          400: 'var(--ui-red400)',
          500: 'var(--ui-red500)',
          600: 'var(--ui-red600)',
          700: 'var(--ui-red700)',
          800: 'var(--ui-red800)',
          900: 'var(--ui-red900)',
          950: 'var(--ui-red950)',
        },
        'ui-yellow': {
          50: 'var(--ui-yellow50)',
          100: 'var(--ui-yellow100)',
          200: 'var(--ui-yellow200)',
          300: 'var(--ui-yellow300)',
          400: 'var(--ui-yellow400)',
          500: 'var(--ui-yellow500)',
          600: 'var(--ui-yellow600)',
          700: 'var(--ui-yellow700)',
          800: 'var(--ui-yellow800)',
          900: 'var(--ui-yellow900)',
          950: 'var(--ui-yellow950)',
        },
        'ui-green': {
          50: 'var(--ui-green50)',
          100: 'var(--ui-green100)',
          200: 'var(--ui-green200)',
          300: 'var(--ui-green300)',
          400: 'var(--ui-green400)',
          500: 'var(--ui-green500)',
          600: 'var(--ui-green600)',
          700: 'var(--ui-green700)',
          800: 'var(--ui-green800)',
          900: 'var(--ui-green900)',
          950: 'var(--ui-green950)',
        },
        dropShadow: {
          popup: 'var(--popup)',
          fab: 'var(--fab)',
          bnb: 'var(--bnb)',
          pin: 'var(--pin)',
          toggle: 'var(--toggle)',
          toast: 'var(--toast)',
        },
      },
    },
  },
  plugins: [
    require('tailwindcss-animate'),
    require('@tailwindcss/typography'),
    function ({ addUtilities }: { addUtilities: any }) {
      addUtilities({
        '.typography-7-bold': {
          fontWeight: '600',
          fontSize: '20px',
          lineHeight: '28px',
          letterSpacing: '-0.08px',
        },
        '.typography-7-medium': {
          fontWeight: '500',
          fontSize: '20px',
          lineHeight: '28px',
          letterSpacing: '-0.08px',
        },
        '.typography-7-regular': {
          fontWeight: '400',
          fontSize: '20px',
          lineHeight: '28px',
          letterSpacing: '-0.08px',
        },

        '.typography-6-bold': {
          fontWeight: '600',
          fontSize: '18px',
          lineHeight: '26px',
          letterSpacing: '-0.4px',
        },
        '.typography-6-medium': {
          fontWeight: '500',
          fontSize: '18px',
          lineHeight: '26px',
          letterSpacing: '-0.4px',
        },
        '.typography-6-regular': {
          fontWeight: '400',
          fontSize: '18px',
          lineHeight: '26px',
          letterSpacing: '-0.04px',
        },

        '.typography-5-bold': {
          fontWeight: '700',
          fontSize: '16px',
          lineHeight: '24px',
          letterSpacing: '0',
        },
        '.typography-5-medium': {
          fontWeight: '500',
          fontSize: '16px',
          lineHeight: '24px',
          letterSpacing: '0',
        },
        '.typography-5-regular': {
          fontWeight: '400',
          fontSize: '16px',
          lineHeight: '24px',
          letterSpacing: '0',
        },

        '.typography-4-bold': {
          fontWeight: '600',
          fontSize: '14px',
          lineHeight: '20px',
          letterSpacing: '0',
        },
        '.typography-4-medium': {
          fontWeight: '500',
          fontSize: '14px',
          lineHeight: '20px',
          letterSpacing: '0',
        },
        '.typography-4-regular': {
          fontWeight: '400',
          fontSize: '14px',
          lineHeight: '20px',
          letterSpacing: '0',
        },

        '.typography-3-bold': {
          fontWeight: '600',
          fontSize: '12px',
          lineHeight: '16px',
          letterSpacing: '0.04px',
        },
        '.typography-3-medium': {
          fontWeight: '500',
          fontSize: '12px',
          lineHeight: '16px',
          letterSpacing: '0.04px',
        },
        '.typography-3-regular': {
          fontWeight: '400',
          fontSize: '12px',
          lineHeight: '16px',
          letterSpacing: '0.04px',
        },

        '.typography-2-bold': {
          fontWeight: '600',
          fontSize: '10px',
          lineHeight: '20px',
          letterSpacing: '0',
        },
        '.typography-2-medium': {
          fontWeight: '500',
          fontSize: '10px',
          lineHeight: '20px',
          letterSpacing: '0',
        },
        '.typography-2-regular': {
          fontWeight: '400',
          fontSize: '10px',
          lineHeight: '20px',
          letterSpacing: '0',
        },

        '.typography-1-bold': {
          fontWeight: '600',
          fontSize: '8px',
          lineHeight: '12px',
          letterSpacing: '0.04px',
        },
        '.typography-1-medium': {
          fontWeight: '500',
          fontSize: '8px',
          lineHeight: '12px',
          letterSpacing: '0.04px',
        },
        '.typography-1-regular': {
          fontWeight: '400',
          fontSize: '8px',
          lineHeight: '12px',
          letterSpacing: '0.04px',
        },
        '.typography-1-light': {
          fontWeight: '350',
          fontSize: '8px',
          lineHeight: '12px',
          letterSpacing: '0.04px',
        },
      });
    },
  ],
} satisfies Config;
